# Generated by Django 5.2 on 2025-05-03 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('is_played', models.BooleanField(default=False)),
                ('is_playoff', models.BooleanField(default=False)),
                ('playoff_stage', models.CharField(blank=True, max_length=20, null=True)),
                ('match_time', models.DateTimeField(blank=True, null=True)),
                ('away_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.player')),
                ('home_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.player')),
            ],
        ),
    ]
